# A basic script template for revisions.
revision = '12c381b2427e'
down_revision = '654de95c33a5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'customer_id')
    # ### end Alembic commands ###
