# A basic script template for revisions.
revision = '78c71023fc4a'
down_revision = 'init_schema'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kots_tenant_id'), 'kots', ['tenant_id'], unique=False)
    op.drop_constraint('global_users_email_key', 'global_users', type_='unique')
    op.drop_constraint('global_users_phone_key', 'global_users', type_='unique')
    op.create_index(op.f('ix_global_users_email'), 'global_users', ['email'], unique=True)
    op.create_index(op.f('ix_global_users_phone'), 'global_users', ['phone'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_global_users_phone'), table_name='global_users')
    op.drop_index(op.f('ix_global_users_email'), table_name='global_users')
    op.create_unique_constraint('global_users_phone_key', 'global_users', ['phone'])
    op.create_unique_constraint('global_users_email_key', 'global_users', ['email'])
    op.drop_index(op.f('ix_kots_tenant_id'), table_name='kots')
    op.drop_table('kots')
    # ### end Alembic commands ###
